lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
    plug :put_user_token


  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    resources "/messages", MessageController
    resources "/users", UserController
    resources "/follows", FollowController

    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout

    get "/", PageController, :index
    get "/feed", FeedController, :show
    get "/welcome", WelcomeController, :show
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", MicroblogWeb do
    pipe_through :api

    resources "/likes", LikeController, except: [:new, :edit]

  end
end

lib/microblog/blog/message.ex
defmodule Microblog.Blog.Message do
  use Ecto.Schema
  import Ecto.Changeset
  alias Microblog.Blog.Message


  schema "messages" do
    field :desc, :string
    belongs_to :user, Microblog.Blog.User
    timestamps()
  end

  @doc false
  def changeset(%Message{} = message, attrs) do
    message
    |> cast(attrs, [:desc, :user_id])
    |> validate_required([:desc])
  end
end

lib/microblog_web/controllers/message_controller.ex
defmodule MicroblogWeb.MessageController do
  use MicroblogWeb, :controller

  alias Microblog.Blog
  alias Microblog.Blog.Message

  def index(conn, _params) do
    messages = Blog.list_messages()
    changeset = Blog.change_message(%Message{})

    render(conn, "index.html", messages: messages, changeset: changeset)
  end

  def new(conn, _params) do
    changeset = Blog.change_message(%Message{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"message" => message_params}) do
    IO.inspect(message_params)
    case Blog.create_message(message_params) do
      {:ok, message} ->
        conn
        |> put_flash(:info, "Message created successfully.")
        |> redirect(to: message_path(conn, :show, message))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    message = Blog.get_message!(id)
    current_user = conn.assigns[:current_user]
    changeset = Blog.change_message(%Microblog.Blog.Message{user_id: current_user.id})
    render(conn, "show.html", current_user: current_user, message: message, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    message = Blog.get_message!(id)
    changeset = Blog.change_message(message)
    render(conn, "edit.html", message: message, changeset: changeset)
  end

  def update(conn, %{"id" => id, "message" => message_params}) do
    message = Blog.get_message!(id)

    case Blog.update_message(message, message_params) do
      {:ok, message} ->
        conn
        |> put_flash(:info, "Message updated successfully.")
        |> redirect(to: message_path(conn, :show, message))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", message: message, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    message = Blog.get_message!(id)
    {:ok, _message} = Blog.delete_message(message)

    conn
    |> put_flash(:info, "Message deleted successfully.")
    |> redirect(to: message_path(conn, :index))
  end
end

lib/microblog_web/views/message_view.ex
defmodule MicroblogWeb.MessageView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/message/edit.html.eex
<h2>Edit Message</h2>

<%= render "form.html", Map.put(assigns, :action, message_path(@conn, :update, @message)) %>

<span><%= link "Back", to: message_path(@conn, :index) %></span>

lib/microblog_web/templates/message/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= if @current_user do %>
  <div id="message-user"
       data-current_email="<%= @current_user.user_email %>"
       data-current_id="<%= @current_user.id %>">
    &nbsp;
  </div>
  <% end %>
  
  <div id="msg-field" class="form-group">
    <%= label f, :desc, class: "control-label" %>
    <%= text_input f, :desc, class: "form-control" %>
    <%= error_tag f, :desc %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/microblog_web/templates/message/index.html.eex
<!-- dashboard panel, with all messages  -->
<div class="container-fluid">
  <div class="row">
    <%= if @current_user do %>

    <div class="col-md-4">

      <!-- showing current user and posting new messages -->
      <!-- create a new message  -->
      <h2> New Message </h2>

      <%= form_for @changeset, message_path(@conn, :create), fn f -> %>
      <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
      <% end %>

      <%= hidden_input f, :user_id, value: @current_user.id %>
      <%= hidden_input f, :user_email, value: @current_user.user_email %>

      <div id="msg-field" class="form-group">
        <%= label f, :desc, class: "control-label" %>
        <%= text_input f, :desc, class: "form-control" %>
        <%= error_tag f, :desc %>
      </div>

      <%= if @current_user do %>
      <div id="msg-user"
      data-current_email="<%= @current_user.user_email %>"
      data-current_id="<%= @current_user.id %>">
      &nbsp;
    </div>
    <% end %>

    <div id="msg-submit" class="form-group">
      <%= submit "Submit", class: "btn btn-primary" %>
    </div>
    <% end %>

  </div>

  <% end %>

  <div class="col-md-8 ml-auto">

    <h2>Listing Messages</h2>

    <table id="messages-index-container" class="table">
      <thead>
        <tr>
          <th>Desc</th>

          <th>Id</th>
        </tr>
      </thead>
      <tbody>
        <%= for message <- @messages do %>
        <tr>
          <td><%= message.desc %></td>
          <td><%= message.user_id %></td>
          <%= if @current_user do %>
          <td class="text-right">
            <span><%= link "Show", to: message_path(@conn, :show, message), class: "btn btn-default btn-xs" %></span>
            <%= if matchUser?(@current_user, message) do %>
            <span><%= link "Edit", to: message_path(@conn, :edit, message), class: "btn btn-default btn-xs" %></span>
            <% end %>
            <%= if authorized?(@current_user) do %>
            <span><%= link "Delete", to: message_path(@conn, :delete, message), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

    <!-- <span><%= link "New Message", to: message_path(@conn, :new) %></span> -->


  </div>
</div>
</div>

lib/microblog_web/templates/message/new.html.eex
<h2>New Message</h2>

<%= render "form.html", Map.put(assigns, :action, message_path(@conn, :create)) %>

<span><%= link "Back", to: message_path(@conn, :index) %></span>

lib/microblog_web/templates/message/show.html.eex
<h2>Show Message</h2>


<ul>

  <li>
    <strong>Desc:</strong>
    <%= @message.desc %>
  </li>
  <li>
    <strong>User_id:</strong>
    <%= @message.user_id %>
  </li>

</ul>

<div id="message-likes"
data-path="<%= like_path(@conn, :index) %>"
data-message_id="<%= @message.id %>">
&nbsp;
</div>

<script id="likes-template" type="text/x-handlebars-template">
  <div class="m-2">
    <h2>Likes</h2>

    {{#each data}}
    <div class="card w-75 m-2">
      <div class="card-body">
        <h6 class=""></h6>
        <div class="card-text">
          <p>{{user_email}} liked this post</p>
        </div>
      </div>
    </div>
    {{/each}}
  </div>
</script>

<%= if @current_user do %>
<div class="m-2">
  <h2>Add Like</h2>
  <button id="like-add-button" class="btn btn-primary"
  data-user_id="<%= @current_user.id %>"
  data-user_email="<%= @current_user.user_email %>">Like</button>
  <button id="like-delete-button" class="btn btn-warning"
  data-user_id="<%= @current_user.id %>"
  data-user_email="<%= @current_user.user_email %>">Unlike</button>
</div>
<% end %>

<span><%= link "Edit", to: message_path(@conn, :edit, @message) %></span>
<span><%= link "Back", to: message_path(@conn, :index) %></span>