lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
    plug :put_user_token


  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    resources "/messages", MessageController
    resources "/users", UserController
    resources "/follows", FollowController

    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout

    get "/", PageController, :index
    get "/feed", FeedController, :show
    get "/welcome", WelcomeController, :show
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", MicroblogWeb do
    pipe_through :api

    resources "/likes", LikeController, except: [:new, :edit]

  end
end

lib/microblog/blog/user.ex
defmodule Microblog.Blog.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Microblog.Blog
  alias Microblog.Blog.User
  alias Microblog.Blog.Message
  alias Microblog.Blog.Follow

  schema "users" do
    field :user_email, :string
    field :authorized, :boolean

    has_many :messages, Message
    has_many :follows, Follow
    # added for password hash
    field :password_hash, :string
    field :pw_tries, :integer
    field :pw_last_try, :utc_datetime

    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true

    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:user_email, :authorized, :password, :password_confirmation])
    |> validate_confirmation(:password)
    |> validate_password(:password)
    |> put_pass_hash()
    |> validate_required([:user_email, :password_hash])
  end

  # code from Nat Tuck's lecture notes
  # Password validation
  # From Comeonin docs
  def validate_password(changeset, field, options \\ []) do
    validate_change(changeset, field, fn _, password ->
      case valid_password?(password) do
        {:ok, _} -> []
        {:error, msg} -> [{field, options[:message] || msg}]
      end
    end)
  end

  def put_pass_hash(%Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset) do
    change(changeset, Comeonin.Argon2.add_hash(password))
  end
  def put_pass_hash(changeset), do: changeset

  def valid_password?(password) when byte_size(password) > 7 do
    {:ok, password}
  end
  def valid_password?(_), do: {:error, "The password is too short"}
  def get_and_auth_user(email, password) do
    user = Blog.get_user_by_email!(email)
    case Comeonin.Argon2.check_pass(user, password) do
      {:ok, user} -> user
      _else       -> nil
    end
  end
end

lib/microblog_web/controllers/user_controller.ex
defmodule MicroblogWeb.UserController do
  use MicroblogWeb, :controller

  alias Microblog.Blog
  alias Microblog.Blog.User

  def index(conn, _params) do
    users = Blog.list_users()

    current_user = conn.assigns[:current_user]
    # show index needs authorization
    if (current_user != nil) do
      if (current_user.authorized) do
        render(conn, "index.html", users: users)
      else
        conn
        |> redirect(to: "/")
        |> halt()
      end
    else
      conn
      |> redirect(to: "/")
      |> halt()
    end
  end

  def new(conn, _params) do
    changeset = Blog.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Blog.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: welcome_path(conn, :show))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Blog.get_user!(id)
    current_user = conn.assigns[:current_user]
    message = Blog.change_message(%Microblog.Blog.Message{user_id: id})
    follow = Blog.change_follow(%Microblog.Blog.Follow{following_user_id: id, follower_user_id: current_user.id})
    render(conn, "show.html", user: user, message: message, follow: follow)
  end

  def edit(conn, %{"id" => id}) do
    user = Blog.get_user!(id)
    changeset = Blog.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Blog.get_user!(id)

    case Blog.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Blog.get_user!(id)
    {:ok, _user} = Blog.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

lib/microblog_web/views/user_view.ex
defmodule MicroblogWeb.UserView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/microblog_web/templates/user/form.html.eex
<div class="container-fluid">
  <br />
  <div class="row">
    <div class="col-md-12 mx-auto">
      <h3>who are you?</h3>
    </div>
    <div class="col-md-6 mx-auto">
      <%= form_for @changeset, @action, fn f -> %>
        <%= if @changeset.action do %>
          <div class="alert alert-danger">
            <p>Oops, something went wrong! Please check the errors below.</p>
          </div>
        <% end %>

        <div class="form-group">
          <%= label f, :user_email, class: "control-label" %>
          <%= text_input f, :user_email, class: "form-control" %>
          <%= error_tag f, :user_email %>
        </div>

        <!-- adding password  -->
        <div class="form-group">
          <%= label f, :password, class: "control-label" %>
          <%= password_input f, :password, class: "form-control" %>
          <%= error_tag f, :password %>
        </div>

        <div class="form-group">
          <%= label f, :password_confirmation, class: "control-label" %>
          <%= password_input f, :password_confirmation, class: "form-control" %>
          <%= error_tag f, :password_confirmation %>
        </div>

        <div class="form-group">
          <%= submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>

lib/microblog_web/templates/user/index.html.eex
<h2>Listing Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>User email</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.user_email %></td>

      <td class="text-right">
        <span><%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: user_path(@conn, :new) %></span>

lib/microblog_web/templates/user/new.html.eex
<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/microblog_web/templates/user/show.html.eex
<!-- user card -->
  <h2>Show User</h2>

  <ul>

    <li>
      <strong>User email:</strong>
      <%= @user.user_email %>
    </li>

  </ul>

  <!-- no permission to edit email if not admin  -->
  <!-- <span><%= link "Edit", to: user_path(@conn, :edit, @user) %></span> -->
  <span><%= link "Back", to: user_path(@conn, :index) %></span>

<!-- follow this user, should not follow itself -->
<%= form_for @follow, follow_path(@conn, :create), fn f -> %>
<%= if @follow.action do %>
<div class="alert alert-danger">
  <p>Oops, something went wrong! Please check the errors below.</p>
</div>
<% end %>

<%= hidden_input f, :following_user_id %>
<%= hidden_input f, :follower_user_id %>

<div class="form-group">
  <%= submit "Follow User", class: "btn btn-primary" %>
</div>
<% end %>

<!-- dashboard panel, with all messages  -->
<!-- <div class="col-md-8 ml-auto">
</div> -->