lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
    plug :put_user_token


  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    resources "/messages", MessageController
    resources "/users", UserController
    resources "/follows", FollowController

    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout

    get "/", PageController, :index
    get "/feed", FeedController, :show
    get "/welcome", WelcomeController, :show
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", MicroblogWeb do
    pipe_through :api

    resources "/likes", LikeController, except: [:new, :edit]

  end
end

lib/microblog_web/views/layout_view.ex
defmodule MicroblogWeb.LayoutView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Hello Microblog!</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>

</head>

<body>
  <nav class="navbar navbar-light bg-light navbar-expand-md">
    <a class="navbar-brandk">
      <%= link "Word", to: welcome_path(@conn, :show),
      class: "nav-link text-dark font-weight-bold"%>
    </a>
    <button class="navbar-toggler" type="button"
    data-toggle="collapse" data-target="#main-navbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="main-navbar">
    <ul class="navbar-nav mr-auto">
      <!-- News feed -->
      <li class="nav-item">
        <%= link "Dashboard", to: message_path(@conn, :index), class: "nav-link"%>
      </li>
      <!-- For looking at the user's own info -->
      <%= if @current_user do %>

      <li class="nav-item">
        <%= link "Profile", to: user_path(@conn, :show, @current_user.id), class: "nav-link" %>
      </li>
      <% end %>
      <!-- For looking at the users this user is following -->
      <li class="nav-item">
        <%= link "Chat", to: feed_path(@conn, :show), class: "nav-link" %>
      </li>
    </ul>
  </div>

  <%= if @current_user do %>
  <span class="text-light">
    <%= @current_user.user_email %> |
    <%= link("logout", to: session_path(@conn, :logout), method: :delete) %>
  </span>
  <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  <% else %>
  <%= form_for @conn, session_path(@conn, :login), [as: "user", class: "form-inline w-75"], fn f -> %>
  <input type="text" placeholder="email" class="form-control" name="email">
  <input type="password" placeholder="password" class="form-control" name="password">
  <%= submit "Log in", class: "btn btn-primary" %>
  <% end %>
  <% end %>
</nav>

<div class="container">

  <div class="row">
    <div class="col-sm-12 my-2">
      <%= if get_flash(@conn, :info) do %>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </div>


</div> <!-- /container -->
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>

</body>
</html>